org.gradle.jvmargs=-Xmx8G -Dorg.gradle.logging.level=warn -Djava.util.concurrent.ForkJoinPool.common.parallelism=1
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Mod Properties
mod_id=immersivetechnology
mod_name=Immersive Technology
mod_authors=tgstyle
mod_license=LGPL-3.0
mod_description=Immersive Technology for 1.21.1.
