modLoader="javafml"
loaderVersion="[1,)"
license="LGPL-3.0"

[[mods]]
modId = "immersivetechnology"
version = "${version}"
displayName = "Immersive Technology"
description = "An in development version of Immersive Technology for 1.21.1."
authors = "tgstyle"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/mct-immersive-technology"
logoFile = "logo.png"
credits = "tgstyle (author), Peter (new models), KHAZ (new sounds), and the Immersive Engineering Team (code dependencies)"

[[dependencies.immersivetechnology]]
modId="neoforge"
mandatory=true
versionRange="[${version_neoforge_min},)"
ordering="NONE"
side="BOTH"

[[dependencies.immersivetechnology]]
modId="minecraft"
mandatory=true
versionRange="[${version_mc}]"
ordering="NONE"
side="BOTH"

[[dependencies.immersivetechnology]]
modId="immersiveengineering"
mandatory=true
versionRange="[${version_ie},]"
ordering="NONE"
side="BOTH"

[[dependencies.immersivetechnology]]
modId="immersiveconvergence"
mandatory=true
versionRange="${version_ic}"
ordering="NONE"
side="BOTH"

[[mixins]]
config="mixins.immersivetechnology.json"
